# Generated by Django 3.2.12 on 2022-12-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20221213_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_photo_5',
            field=models.ImageField(blank=True, upload_to='pages/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_photo_1',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
    ]
