# Generated by Django 3.2.12 on 2022-12-14 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_car_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='no_of_owners',
            field=models.CharField(choices=[('1', 'First owner'), ('2', 'Second owner'), ('3', 'Third owner'), ('4', 'Fourth owner'), ('5', 'Fifth owner')], max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='seats',
            field=models.CharField(choices=[('2', '2'), ('4', '4'), ('5', '5'), ('7', '7'), ('9', '9'), ('12', '12')], max_length=100),
        ),
    ]
